### ISSUE TITLE
Text layout support

### ISSUE THREAD

**Issue by noelwelsh** [creativescala/doodle#173]
We need to support some form of text layout, so that text boxes can be restricted in width or height or both, and text will reflow to fit within the constraints. There is an example of reflowing [here](https://skia.org/docs/user/modules/canvaskit/) (the paragraph shaping demo).

### Tasks

* [ ] See what current APIs (Java2D, Skia, SVG, etc.) support to get an idea of what is available
* [ ] Design an API to represent minimal functionality
* [ ] Implement it for one or more backends!
